### ISSUE TITLE
SyntaxError: Unexpected token ) trying to follow readme

### ISSUE THREAD

**Issue by xCmac** [cdimascio/generator-express-no-stress#15]
> ~/Documents $ node -v
v6.11.2
~/Documents $ yo express-no-stress myapp
/usr/local/lib/node_modules/generator-express-no-stress/app/index.js:108
          );
          ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as express-no-stress:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)

I'm on node 6 as required. Any suggestions?

**Comment by cdimascio** [comment]
this is likely an issue with trailing commas. i cleaned them up. can you give version 3.4.11 a try

**Comment by xCmac** [comment]
Thanks for the quick fix, looks like that did it.

**Comment by cdimascio** [comment]
@xCmac excellent. thanks for verifying
