### ISSUE TITLE
Getting error on missing test folder

### ISSUE THREAD

**Issue by TigerTurnedLion** [cdimascio/generator-express-no-stress#39]
Hello

Love your style and want to use your generator.  

After the following steps:

`
$ npm install -g generator-express-no-stress
`
`
$ yo express-no-stress api2die
`

I am getting the following error message in regards to missing test folder.  
Here is the output:

johns-mbp:LOL johnkelly$ yo express-no-stress api2die
? App description [My cool app] api for laughs
? API Root [/api/v1] 
? Version [1.0.0] 
? OpenAPI spec version OpenApi 3
? Linter Prettier
events.js:187
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-express-no-stress/app/templates/test/examples.controller.js
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-express-no-stress/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-express-no-stress/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at /usr/local/lib/node_modules/generator-express-no-stress/app/index.js:141:19
    at Array.forEach (<anonymous>)
    at module.exports.appStaticFiles (/usr/local/lib/node_modules/generator-express-no-stress/app/index.js:140:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-express-no-stress/node_modules/yeoman-generator/lib/index.js:395:23)
    at /usr/local/lib/node_modules/generator-express-no-stress/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-express-no-stress/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-express-no-stress/node_modules/yeoman-generator/lib/index.js:396:9
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-express-no-stress/node_modules/yeoman-generator/lib/index.js:404:18)
    at processImmediate (internal/timers.js:439:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Tried sudo with same results.

**Comment by cdimascio** [comment]
@TigerTurnedLion thanks so much for the issue. Looking at it now

**Comment by cdimascio** [comment]
This is now resolved in 8.4.1
