### ISSUE TITLE
npm run compile error, exit status 1

### ISSUE THREAD

**Issue by hackerunet** [cdimascio/generator-express-no-stress#63]
I got an error in npm run compile to build the production application:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/hackerunet/.nvm/versions/node/v10.9.0/bin/node',
1 verbose cli   '/home/hackerunet/.nvm/versions/node/v10.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@6.10.3
3 info using node@v10.9.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle indicators@1.0.0~precompile: indicators@1.0.0
6 info lifecycle indicators@1.0.0~compile: indicators@1.0.0
7 verbose lifecycle indicators@1.0.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle indicators@1.0.0~compile: PATH: /home/hackerunet/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators/node_modules/.bin:/home/hackerunet/.composer/vendor/bin:/home/hackerunet/software/google-cloud-sdk/bin:/home/hackerunet/.pyenv/shims:/home/hackerunet/.pyenv/bin:/home/hackerunet/.ebcli-virtual-env/executables:/home/hackerunet/software/flutter/bin:/home/hackerunet/.nvm/versions/node/v10.9.0/bin:/home/hackerunet/.local/bin:/home/hackerunet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/hackerunet/android/sdk/platform-tools/adb:/home/hackerunet/android/sdk/platform-tools:/home/hackerunet/.composer/vendor/bin:/usr/lib/dart/bin:/home/hackerunet/.pub-cache/bin:/home/hackerunet/software/terraform/bin:/home/hackerunet/.local/lib/aws/bin
9 verbose lifecycle indicators@1.0.0~compile: CWD: /home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators
10 silly lifecycle indicators@1.0.0~compile: Args: [ '-c',
10 silly lifecycle   'babel server --out-dir dist --delete-dir-on-start --source-maps inline --copy-files' ]
11 silly lifecycle indicators@1.0.0~compile: Returned: code: 1  signal: null
12 info lifecycle indicators@1.0.0~compile: Failed to exec compile script
13 verbose stack Error: indicators@1.0.0 compile: `babel server --out-dir dist --delete-dir-on-start --source-maps inline --copy-files`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/hackerunet/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/hackerunet/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid indicators@1.0.0
15 verbose cwd /home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators
16 verbose Linux 4.15.0-109-generic
17 verbose argv "/home/hackerunet/.nvm/versions/node/v10.9.0/bin/node" "/home/hackerunet/.nvm/versions/node/v10.9.0/bin/npm" "run" "compile"
18 verbose node v10.9.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error indicators@1.0.0 compile: `babel server --out-dir dist --delete-dir-on-start --source-maps inline --copy-files`
22 error Exit status 1
23 error Failed at the indicators@1.0.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```
Honnestly I have no idea what is going on, apparently something related with babel but not sure if there is something missing in my required libraries.
Thanks

Running the compile command with yarn i got this:
```
hackerunet@kerberobot:~/Projects/SuperPesos/super-shoppers-be/indicators$ yarn run compile
yarn run v1.22.10
warning package.json: No license field
$ babel server --out-dir dist --delete-dir-on-start --source-maps inline --copy-files
{ Error: ENOENT: no such file or directory, mkdir 'dist/api/controllers/indicators'
    at mkdirSync (fs.js:729:3)
    at outputFileSync (/home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators/node_modules/@babel/cli/lib/babel/dir.js:68:100)
    at /home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators/node_modules/@babel/cli/lib/babel/dir.js:114:11
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators/node_modules/@babel/cli/lib/babel/dir.js:56:103)
    at _next (/home/hackerunet/Projects/SuperPesos/super-shoppers-be/indicators/node_modules/@babel/cli/lib/babel/dir.js:58:194)
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'dist/api/controllers/indicators' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cdimascio** [comment]
fixed in v11
